# Generated by Django 2.1.5 on 2021-04-06 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20200812_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_visited',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
